name: Update devcontainer.json on Release

on:
  workflow_dispatch:
  release:
    types: [created] # Runs only when a new release is created

permissions:
  contents: write  # Allow the workflow to push changes to the repository
  pull-requests: write  # Allow the workflow to create pull requests

jobs:
  update-version:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v4

    # Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    # Run the script to update the version in devcontainer.json
    - name: Update devcontainer.json with new version
      run: |
        #!/bin/bash

        # Fetch the version from pyproject.toml
        VERSION=$(grep 'version =' pyproject.toml | head -n 1 | sed -E 's/version = "([^\"]+)"/\1/')

        # Debug the version extracted
        echo "Extracted VERSION: $VERSION"

        # Escape any special characters in VERSION that could cause issues with sed (like `/` or `:`)
        VERSION_ESCAPED=$(echo "$VERSION" | sed 's/[&/\]/\\&/g')

        # Update the version in devcontainer.json
        # Using the escaped version to safely substitute in the JSON file
        sed -i -E "s|ghcr.io/autoatml/autoplex/autoplex-python-3.10:[^\"]*|ghcr.io/autoatml/autoplex/autoplex-python-3.10:$VERSION_ESCAPED|" .devcontainer/devcontainer.json

        echo "Updated devcontainer.json with version $VERSION"

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v7
      with:
        commit-message: update devcontainer
        title: Update devcontainer.json version tag
        body: Update devcontainer.json version tag to reflect release changes
        branch: update-devcontainer
        delete-branch: true
        base: main
